name: Playwright Tests

on:
  push:
    branches: ["main", "principal", "master"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout automação
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps (automação)
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      
      - name: Start stack (docker compose)
        run: docker compose -f docker-compose.ci.yml up -d --build

      - name: Wait services
        run: npx wait-on http://localhost:3030 http://localhost:3000

      - name: Run Playwright tests
        env:
          BASE_URL_API: http://localhost:3030
          BASE_URL_WEB: http://localhost:3000
        run: npx playwright test

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

     
      - name: Upload docker logs
        if: always()
        run: |
          docker compose -f docker-compose.ci.yml ps
          docker compose -f docker-compose.ci.yml logs --no-color > docker-logs.txt

      - name: Upload docker logs artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: docker-logs
          path: docker-logs.txt

    
      - name: Shutdown stack
        if: always()
        run: docker compose -f docker-compose.ci.yml down -v
